In [20]:
import pandas as pd

In [21]:
df=pd.read_csv("Employee_Performance_Dataset.csv")

import numpy as np

In [3]:
df.head()

,Employee_ID,Age,Gender,Education,Experience,Department,City,Salary,Performance_Rating,Working_Hours,Projects,Attendance,Promotion,Purchased
0,1,22,Male,Bachelor,1,HR,Mumbai,25000,3,8,1,90,No,No
1,2,25,Female,Master,3,IT,Pune,42000,4,9,3,95,Yes,Yes
2,3,30,Male,Bachelor,6,Sales,Delhi,65000,5,9,5,97,Yes,Yes
3,4,28,Female,PhD,5,IT,Mumbai,72000,5,8,4,96,Yes,Yes
4,5,35,Male,Master,10,Finance,Pune,90000,5,10,7,98,Yes,Yes

In [5]:
df.duplicated().sum()

np.int64(0)

In [22]:
dt={"name":["a","b","c","d","a","c"],"age":[12,23,34,45,12,-45],"city":["pune","mumbai","delhi","pune","pune",np.nan]}

In [23]:
data=pd.DataFrame(dt)

In [24]:
data

  name  age    city
0    a   12    pune
1    b   23  mumbai
2    c   34   delhi
3    d   45    pune
4    a   12    pune
5    c  -45     NaN

In [25]:
data.duplicated().sum()

np.int64(1)

In [26]:
data.drop_duplicates(inplace=True)

In [27]:
data

  name  age    city
0    a   12    pune
1    b   23  mumbai
2    c   34   delhi
3    d   45    pune
5    c  -45     NaN

In [30]:
data["city"].fillna(data["city"],method="bfill")

NameError: name 'fillna' is not defined

In [49]:
data["age"].replace(-45,45,inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19392\406592320.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["age"].replace(-45,45,inplace=True)

0    12
1    23
2    34
3    45
5    45
Name: age, dtype: int64

In [35]:
data

  name  age    city
0    a   12    pune
1    b   23  mumbai
2    c   34   delhi
3    d   45    pune
5    c  -45     NaN

In [36]:
data.info()

<class 'pandas.DataFrame'>
Index: 5 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     5 non-null      int64
 2   city    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 160.0 bytes

In [ ]:
city