In [1]:
import numpy as np

In [4]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv("Employee_Performance_Dataset.csv")

In [6]:
df.head()

,Employee_ID,Age,Gender,Education,Experience,Department,City,Salary,Performance_Rating,Working_Hours,Projects,Attendance,Promotion,Purchased
0,1,22,Male,Bachelor,1,HR,Mumbai,25000,3,8,1,90,No,No
1,2,25,Female,Master,3,IT,Pune,42000,4,9,3,95,Yes,Yes
2,3,30,Male,Bachelor,6,Sales,Delhi,65000,5,9,5,97,Yes,Yes
3,4,28,Female,PhD,5,IT,Mumbai,72000,5,8,4,96,Yes,Yes
4,5,35,Male,Master,10,Finance,Pune,90000,5,10,7,98,Yes,Yes

In [ ]:
# single scaler

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
ss=StandardScaler()

In [30]:
df[["Salary"]]=ss.fit_transform(df[["Salary"]])

In [31]:
df.head()

,Employee_ID,Age,Gender,Education,Experience,Department,City,Salary,Performance_Rating,Working_Hours,Projects,Attendance,Promotion,Purchased
0,1,-1.376854,Male,Bachelor,-1.191203,HR,Mumbai,-1.296494,3,8,1,90,No,No
1,2,-0.894687,Female,Master,-0.800645,IT,Pune,-0.807070,4,9,3,95,Yes,Yes
2,3,-0.091076,Male,Bachelor,-0.214807,Sales,Delhi,-0.144908,5,9,5,97,Yes,Yes
3,4,-0.412520,Female,PhD,-0.410086,IT,Mumbai,0.056620,5,8,4,96,Yes,Yes
4,5,0.712535,Male,Master,0.566310,Finance,Pune,0.574834,5,10,7,98,Yes,Yes

In [13]:
#  multiple scaler

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler=StandardScaler()

In [23]:
numeric_columns=["Age","Experience","Performance_Rating","Working_Hours"]

In [28]:
df[numeric_columns]=scaler.fit_transform(df[numeric_columns])

In [29]:
df.head()

,Employee_ID,Age,Gender,Education,Experience,Department,City,Salary,Performance_Rating,Working_Hours,Projects,Attendance,Promotion,Purchased
0,1,-1.376854,Male,Bachelor,-1.191203,HR,Mumbai,-1.296494,3,8,1,90,No,No
1,2,-0.894687,Female,Master,-0.800645,IT,Pune,-0.807070,4,9,3,95,Yes,Yes
2,3,-0.091076,Male,Bachelor,-0.214807,Sales,Delhi,-0.144908,5,9,5,97,Yes,Yes
3,4,-0.412520,Female,PhD,-0.410086,IT,Mumbai,0.056620,5,8,4,96,Yes,Yes
4,5,0.712535,Male,Master,0.566310,Finance,Pune,0.574834,5,10,7,98,Yes,Yes