In [ ]:
# method 1 : z score

In [1]:
import pandas as pd
from scipy.stats import zscore

# Dataset load karo
df = pd.read_csv("IQR_Outlier_Practice_Dataset.csv")

# Salary ka Z-score calculate karo
df["Z_Score"] = zscore(df["Salary"])

# Outliers remove karo
df = df[
    (df["Z_Score"] >= -3) &
    (df["Z_Score"] <= 3)
]

# Z_Score column remove karo
df = df.drop("Z_Score", axis=1)

# Final data print karo
print(df)

    Employee_ID  Age  Experience  Salary  Projects  Attendance
0             1   22           1   25000         1          90
1             2   25           3   42000         3          95
2             3   30           6   65000         5          97
3             4   28           5   72000         4          96
4             5   35          10   90000         7          98
5             6   24           2   30000         2          91
6             7   40          15  120000         9          99
7             8   27           4   50000         3          94
8             9   29           5   55000         4          92
9            10   32           8   80000         6          97
10           11   26           3   38000         2          89
11           12   38          12  110000         8          99
12           13   23           1   28000         1          88
13           14   31           7   70000         5          96
14           15   36          11  100000         7          98
15           16   27           4   47000         3          93
16           17   33           9   85000         6          97
17           18   21           1   24000         1          87
18           19   45          20  150000        10          99
19           20   29           6   62000         4          95
21           22   18           0    5000         0          40

In [ ]:
# method 2 : manual

In [2]:
import pandas as pd

In [4]:
from scipy.stats import zscore

In [5]:
df = pd.read_csv("IQR_Outlier_Practice_Dataset.csv")

In [8]:
mean=df["Salary"].mean()

In [9]:
mean

np.float64(106727.27272727272)

In [10]:
std=df["Salary"].std()

In [11]:
std

np.float64(202617.90966254025)

In [13]:
df["z_score"]=(df["Salary"]-mean)/std

In [14]:
df.shape

(22, 7)

In [21]:
df=df[ (df["z_score"] >= -3 )& (df["z_score"] <= 3)
    ]
df

    Employee_ID  Age  Experience  Salary  Projects  Attendance   z_score
0             1   22           1   25000         1          90 -0.403357
1             2   25           3   42000         3          95 -0.319455
2             3   30           6   65000         5          97 -0.205941
3             4   28           5   72000         4          96 -0.171393
4             5   35          10   90000         7          98 -0.082556
5             6   24           2   30000         2          91 -0.378680
6             7   40          15  120000         9          99  0.065506
7             8   27           4   50000         3          94 -0.279972
8             9   29           5   55000         4          92 -0.255295
9            10   32           8   80000         6          97 -0.131910
10           11   26           3   38000         2          89 -0.339196
11           12   38          12  110000         8          99  0.016152
12           13   23           1   28000         1          88 -0.388550
13           14   31           7   70000         5          96 -0.181264
14           15   36          11  100000         7          98 -0.033202
15           16   27           4   47000         3          93 -0.294778
16           17   33           9   85000         6          97 -0.107233
17           18   21           1   24000         1          87 -0.408292
18           19   45          20  150000        10          99  0.213568
19           20   29           6   62000         4          95 -0.220747
21           22   18           0    5000         0          40 -0.502065

In [20]:
df

    Employee_ID  Age  Experience  Salary  Projects  Attendance   z_score
0             1   22           1   25000         1          90 -0.403357
1             2   25           3   42000         3          95 -0.319455
2             3   30           6   65000         5          97 -0.205941
3             4   28           5   72000         4          96 -0.171393
4             5   35          10   90000         7          98 -0.082556
5             6   24           2   30000         2          91 -0.378680
6             7   40          15  120000         9          99  0.065506
7             8   27           4   50000         3          94 -0.279972
8             9   29           5   55000         4          92 -0.255295
9            10   32           8   80000         6          97 -0.131910
10           11   26           3   38000         2          89 -0.339196
11           12   38          12  110000         8          99  0.016152
12           13   23           1   28000         1          88 -0.388550
13           14   31           7   70000         5          96 -0.181264
14           15   36          11  100000         7          98 -0.033202
15           16   27           4   47000         3          93 -0.294778
16           17   33           9   85000         6          97 -0.107233
17           18   21           1   24000         1          87 -0.408292
18           19   45          20  150000        10          99  0.213568
19           20   29           6   62000         4          95 -0.220747
21           22   18           0    5000         0          40 -0.502065